# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.nck.com:
  peer0.warehouse.nck.com:
  peer1.warehouse.nck.com:
  peer0.supplier.nck.com:
  peer1.supplier.nck.com:
  peer0.issuer.nck.com:
  peer1.issuer.nck.com:

networks:
  byfn:

services:

  orderer.nck.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.nck.com
    container_name: orderer.nck.com
    networks:
      - byfn

  peer0.warehouse.nck.com:
    container_name: peer0.warehouse.nck.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.warehouse.nck.com
    networks:
      - byfn

  peer1.warehouse.nck.com:
    container_name: peer1.warehouse.nck.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.warehouse.nck.com
    networks:
      - byfn

  peer0.supplier.nck.com:
    container_name: peer0.supplier.nck.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.supplier.nck.com
    networks:
      - byfn

  peer1.supplier.nck.com:
    container_name: peer1.supplier.nck.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.supplier.nck.com
    networks:
      - byfn

  peer0.issuer.nck.com:
    container_name: peer0.issuer.nck.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.issuer.nck.com
    networks:
      - byfn

  peer1.issuer.nck.com:
    container_name: peer1.issuer.nck.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.issuer.nck.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.warehouse.nck.com:7051
      - CORE_PEER_LOCALMSPID=WarehouseMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/warehouse.nck.com/peers/peer0.warehouse.nck.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/warehouse.nck.com/peers/peer0.warehouse.nck.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/warehouse.nck.com/peers/peer0.warehouse.nck.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/warehouse.nck.com/users/Admin@warehouse.nck.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../smartcontracts:/opt/gopath/src/github.com/contract
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.nck.com
      - peer0.warehouse.nck.com
      - peer1.warehouse.nck.com
      - peer0.supplier.nck.com
      - peer1.supplier.nck.com
      - peer0.issuer.nck.com
      - peer1.issuer.nck.com
    networks:
      - byfn
